services:
  - type: web
    name: m2m-seller
    runtime: python
    pythonVersion: "3.12"
    plan: free
    buildCommand: "echo ok"
    startCommand: "python seller.py"
    healthCheckPath: /status
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: SELLER_USDT_ADDR
        value: TYxynR5V17FYB49osvU3rUkiD7vW2ov634
      - key: M2M_PAYOUT
        value: TYxynR5V17FYB49osvU3rUkiD7vW2ov634
      - key: M2M_PAYMENT_MODE
        value: crypto
      - key: M2M_PAYOUT_THRESHOLD
        value: 10.0
